version: "2"

services:
  web:
    build: .
    restart: always
    image: nsnctf/awd01
    ports:
      - "0.0.0.0:33330:80"
      - "0.0.0.0:44440:22" 
    environment:
      - FLAG=nsnctf{mml_1s_a_g0od_boy}